---
language: node_js
node_js:
  - "9"
script:
  - yarn lint
  - yarn build
  - yarn test
after_script:
  - yarn coverage && cat coverage/lcov.info | coveralls
notifications:
  slack:
    secure: ROidOwDK3i9EJY9x2OojBmVGQYkxxZi92w1AsWfKutDktCaqocXLpjWLuPedTRs3/VFl/1YDMPhYzWQBXzVzlmMJ3kC4EKvZbBAu3C/3M+bDjo/hvqBeDLANn06WVmzKkcCHmhh6YJLK5a7C4ygoy9gS0SAzMC4Ou9ZJ8+V4umBf66//WRwNWZ+MKJ2P2qkuy4M55o3Ke98ozgukPTSuHUdpW4Zwo57C/YiJAy2ZMvda4oKYRmuRu7q0PkilHO+WRGv09CsAwTBCEUJluLva9zJuS1S+x+015LIzrya/3OqLp0ySoDOYD4PnR37H60/Vcvd1SGXXAj13lSZt7ByOVYKxfyQMmTe7CGFbpwgiZXVFUmQTygQeiPH0XZVzM8jxyaCRnUHeyGHunhDhsiDXSQ34Q6db29oH1h4KHMZOoJR0FetVontetZoDi7y6UzFiAvsfLc2CYkg7yukUFcIClmjTUSXt/+yjsLAgq9QviNo9HIvR/OtaoKQkom080jXn//Ntj3JEBbqLg1QIbKjmjpp5LwLRdd1CSoNahIiS07IOQV3kK89av22LX2VD5Ooqggq9VkTevN1T2yT3RoW6k6K9IwjVyQtjLdWbYFg6EbQwptvjl+eRa6D5I1OgkntN5MXGnS3aps3kistKvbv/xvpo8dgaw9bo9BQVBmxEF7Q=
